import type { Metadata } from "next";
import {
  Dosis,
  Geist,
  Geist_Mono,
  Josefin_Sans,
  Poppins,
} from "next/font/google";
import "./globals.css";

const dosis = Dosis({
  variable: "--font-dosis",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

const josefin = Josefin_Sans({
  variable: "--font-josefin",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${dosis.variable} ${poppins.variable} ${josefin.variable} min-h-screen overflow-x-hidden bg-background antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
